version: '3.8'

services:
  greengrass:
    init: false
    container_name: aws-iot-greengrass
    image: greengrassv2included 
    network_mode: "host"
    environment:
      - CONFIG={}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
