version: '3.8'

services:
  greengrass:
    init: false
    container_name: aws-iot-greengrass
    privileged: true
    image: oideibrett/mattercloudcontroller-arm64:2f3e9b2ead264bdb03a0a37f920d2418d28def14
    network_mode: "host"
    ipc: "host"
    environment:
      - AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT=/greengrass/v2/ipc.socket
      - GGC_ROOT_PATH=/greengrass/v2
      - CONFIG={}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /greengrass/v2:/greengrass/v2
      - /var/tmp:/var/tmp
