version: '3.8'

services:
  greengrass:
    init: false
    container_name: aws-iot-greengrass
    image: greengrassv2included 
    network_mode: "host"
    environment:
      - CONFIG={"MCCDev-ThingInstallerStack":{"OutputThingNamePrefix":"mcc-thing-ver01-1","OutputIoTTokenRoleAlias":"MCCDev-GreengrassV2TokenExchangeRoleAlias","OutputInstallerTempRoleARN":"arn:aws:iam::305050752393:role/MCCDev-InstallerTempRole","OutputThingGroupName":"mcc-thing","OutputIoTTokenRole":"MCCDev-GreengrassV2TokenExchangeRole","OutputProjectRegion":"eu-west-1","OutputProjectPrefix":"MCCDev"},"Credentials":{"AccessKeyId":"ASIAUOBTRCWEYCNB7KFY","SecretAccessKey":"9UM6SFQ36Zj7Cc+Rv5Fqc9wElbn0J+esnDjwXnTy","SessionToken":"FwoGZXIvYXdzEPv//////////wEaDOaQQI4nQkFZAGOLoCK6AeQnYZs2FvgWETydJ8ZTo4s7axdvk9/zMA8fU2ffHFg7OnUOtDJWHe6DgJgA9GvZ1msqiEHcwTEvip5W2irMah8v+5RVYKAn2c4dQuIp32KY7xJcZIlO3FYqVG0kU57IvAdogpLlP459kyRsaBK82OR97csUfdKF/KUTMzeIxgSWex6oBPLyo3Q7bRO5XoESN2oMT/NISkp+a6oz3OqzU30Lm7mD9zDdgWkcsUkwvLfv9ZwvEkn5PIWC0Cj/lv6fBjIt0kMVDnncQBHSVuBNghuWZM7CflocZouW0RtskKwbcnzlBU0zU4fZKBknoS4x","Expiration":"2023-03-01 18:29:35+00:00"},"ProjectPrefix":"MCCDev"}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
